/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rental;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_komik = new javax.swing.JButton();
        btn_koran = new javax.swing.JButton();
        btn_Artikel = new javax.swing.JButton();
        btn_majalh = new javax.swing.JButton();
        btn_dongeng = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU UTAMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, -1));

        btn_komik.setBackground(new java.awt.Color(228, 139, 97));
        btn_komik.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_komik.setForeground(new java.awt.Color(255, 255, 255));
        btn_komik.setText("Komik");
        btn_komik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_komikActionPerformed(evt);
            }
        });
        jPanel1.add(btn_komik, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 150, 40));

        btn_koran.setBackground(new java.awt.Color(228, 139, 97));
        btn_koran.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_koran.setForeground(new java.awt.Color(255, 255, 255));
        btn_koran.setText("Koran");
        btn_koran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_koranActionPerformed(evt);
            }
        });
        jPanel1.add(btn_koran, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 150, 40));

        btn_Artikel.setBackground(new java.awt.Color(228, 139, 97));
        btn_Artikel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_Artikel.setForeground(new java.awt.Color(255, 255, 255));
        btn_Artikel.setText("Artikel");
        btn_Artikel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArtikelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Artikel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 150, 40));

        btn_majalh.setBackground(new java.awt.Color(228, 139, 97));
        btn_majalh.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_majalh.setForeground(new java.awt.Color(255, 255, 255));
        btn_majalh.setText("Novel");
        btn_majalh.setMaximumSize(new java.awt.Dimension(63, 25));
        btn_majalh.setMinimumSize(new java.awt.Dimension(63, 25));
        btn_majalh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_majalhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_majalh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 730, 150, 40));

        btn_dongeng.setBackground(new java.awt.Color(228, 139, 97));
        btn_dongeng.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btn_dongeng.setForeground(new java.awt.Color(255, 255, 255));
        btn_dongeng.setText("Dongeng");
        btn_dongeng.setMaximumSize(new java.awt.Dimension(63, 25));
        btn_dongeng.setMinimumSize(new java.awt.Dimension(63, 25));
        btn_dongeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dongengActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dongeng, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 730, 150, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu baru/koran1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu baru/artikel.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu baru/comic.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, 200));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu baru/novel.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 210, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu baru/komik.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/semuadiuseratas.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 160));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/menu.png"))); // NOI18N
        jLabel9.setText(" MENU");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/profil.png"))); // NOI18N
        jLabel10.setText(" PROFILE");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/transaksi.png"))); // NOI18N
        jLabel11.setText(" PEMINJAMAN");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/logout.png"))); // NOI18N
        jLabel12.setText(" LOGOUT");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/bg.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/pinggiran.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_komikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_komikActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new KOMIK().setVisible(true);
    }//GEN-LAST:event_btn_komikActionPerformed

    private void btn_ArtikelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArtikelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ARTIKEL1().setVisible(true);
    }//GEN-LAST:event_btn_ArtikelActionPerformed

    private void btn_koranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_koranActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new KORAN().setVisible(true);
    }//GEN-LAST:event_btn_koranActionPerformed

    private void btn_majalhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_majalhActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new novel().setVisible(true);
    }//GEN-LAST:event_btn_majalhActionPerformed

    private void btn_dongengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dongengActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DONGENG().setVisible(true);
    }//GEN-LAST:event_btn_dongengActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Profil().setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Peminjaman1().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar???", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (ok == 0) {
            new MainMenu().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Artikel;
    private javax.swing.JButton btn_dongeng;
    private javax.swing.JButton btn_komik;
    private javax.swing.JButton btn_koran;
    private javax.swing.JButton btn_majalh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
